"use strict";
var a = null;
// a = 'Chinavanes';
console.log(a);
console.log(typeof a);
var b;
// b = 'Chinavanes';
// b = 12;
var x;
x = 12;
x = 'Chinavanes';
console.log(x);
console.log(typeof x);
var y;
// y = 'Chinavanes';
// y = 12;
y = undefined;
console.log(y);
console.log(typeof y);
var z;
console.log(z);
console.log(typeof z);
console.log(un);
