"use strict";
var isActive = true;
var isUpdated = false;
console.log(isActive);
console.log(typeof isActive);
console.log(isUpdated);
console.log(typeof isUpdated);
var a = true;
var b = false;
console.log(typeof a);
console.log(typeof b);
